# Generated by Django 4.2.7 on 2025-08-18 06:54

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free Plan"),
                            ("starter", "Starter Plan"),
                            ("professional", "Professional Plan"),
                            ("enterprise", "Enterprise Plan"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("max_storage_gb", models.PositiveIntegerField(default=1)),
                ("max_api_calls_per_month", models.PositiveIntegerField(default=1000)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_address", models.TextField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("currency", models.CharField(default="USD", max_length=3)),
            ],
            options={
                "db_table": "public.core_tenant",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#64748B", max_length=7)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("business_hours_start", models.TimeField(default="09:00:00")),
                ("business_hours_end", models.TimeField(default="17:00:00")),
                ("business_days", models.JSONField(default=list)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                ("api_rate_limit", models.PositiveIntegerField(default=100)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=100)),
                ("integrations", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "public.core_tenantsettings",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "domain_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Domain"),
                            ("subdomain", "Subdomain"),
                            ("custom", "Custom Domain"),
                        ],
                        default="subdomain",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_token", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "public.core_domain",
            },
        ),
        migrations.CreateModel(
            name="TenantUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active_users_count", models.PositiveIntegerField(default=0)),
                ("storage_used_gb", models.FloatField(default=0.0)),
                ("api_calls_count", models.PositiveIntegerField(default=0)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("sms_sent", models.PositiveIntegerField(default=0)),
                ("reports_generated", models.PositiveIntegerField(default=0)),
                ("billing_period_start", models.DateTimeField()),
                ("billing_period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "public.core_tenantusage",
                "unique_together": {("tenant", "billing_period_start")},
            },
        ),
    ]
