# Generated by Django 4.2.7 on 2025-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stocklocation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vendormanagedinventory",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_tenant_cat_code",
        ),
        migrations.RemoveConstraint(
            model_name="department",
            name="unique_tenant_dept_code",
        ),
        migrations.RemoveConstraint(
            model_name="productattribute",
            name="unique_tenant_attribute_slug",
        ),
        migrations.RemoveConstraint(
            model_name="stocklocation",
            name="unique_tenant_location_code",
        ),
        migrations.RemoveConstraint(
            model_name="stockreservation",
            name="unique_tenant_reservation_number",
        ),
        migrations.RemoveConstraint(
            model_name="subcategory",
            name="unique_tenant_subcat_code",
        ),
        migrations.RemoveConstraint(
            model_name="unitofmeasure",
            name="unique_tenant_uom_abbrev",
        ),
        migrations.RemoveConstraint(
            model_name="unitofmeasure",
            name="unique_tenant_uom_name",
        ),
        migrations.RemoveConstraint(
            model_name="vendormanagedinventory",
            name="unique_tenant_vmi_number",
        ),
        migrations.RemoveConstraint(
            model_name="vmiproduct",
            name="unique_vmi_product",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="inventory_c_tenant__00f4f9_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="inventory_c_tenant__70de18_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="inventory_d_tenant__2e8a71_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="inventory_d_tenant__d6c6ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="inventory_d_tenant__c2c1de_idx",
        ),
        migrations.RemoveIndex(
            model_name="productattribute",
            name="inventory_p_tenant__585911_idx",
        ),
        migrations.RemoveIndex(
            model_name="productattribute",
            name="inventory_p_tenant__d4002e_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocklocation",
            name="inventory_s_tenant__173d5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocklocation",
            name="inventory_s_tenant__599796_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockreservation",
            name="inventory_s_tenant__401bf6_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockreservation",
            name="inventory_s_tenant__3c089d_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockreservation",
            name="inventory_s_tenant__e3fd0e_idx",
        ),
        migrations.RemoveIndex(
            model_name="subcategory",
            name="inventory_s_tenant__ff5f7a_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendormanagedinventory",
            name="inventory_v_tenant__53fe67_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendormanagedinventory",
            name="inventory_v_tenant__3a4afe_idx",
        ),
        migrations.RemoveIndex(
            model_name="vmiproduct",
            name="inventory_v_tenant__eb8e86_idx",
        ),
        migrations.RemoveIndex(
            model_name="vmiproduct",
            name="inventory_v_tenant__d8aa38_idx",
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant_id", "department", "is_active"],
                name="inventory_c_tenant__00f4f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["tenant_id", "parent"], name="inventory_c_tenant__70de18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant_id", "code"], name="inventory_d_tenant__2e8a71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="inventory_d_tenant__d6c6ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tenant_id", "parent"], name="inventory_d_tenant__c2c1de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="inventory_p_tenant__585911_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["tenant_id", "attribute_type"],
                name="inventory_p_tenant__d4002e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocation",
            index=models.Index(
                fields=["tenant_id", "warehouse", "is_active"],
                name="inventory_s_tenant__173d5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocation",
            index=models.Index(
                fields=["tenant_id", "warehouse", "location_type"],
                name="inventory_s_tenant__599796_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["tenant_id", "status", "expiry_date"],
                name="inventory_s_tenant__401bf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["tenant_id", "reservation_type", "status"],
                name="inventory_s_tenant__3c089d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(
                fields=["tenant_id", "reference_type", "reference_id"],
                name="inventory_s_tenant__e3fd0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["tenant_id", "category", "is_active"],
                name="inventory_s_tenant__ff5f7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendormanagedinventory",
            index=models.Index(
                fields=["tenant_id", "supplier", "status"],
                name="inventory_v_tenant__53fe67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendormanagedinventory",
            index=models.Index(
                fields=["tenant_id", "warehouse", "status"],
                name="inventory_v_tenant__3a4afe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vmiproduct",
            index=models.Index(
                fields=["tenant_id", "vmi_agreement", "is_active"],
                name="inventory_v_tenant__eb8e86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vmiproduct",
            index=models.Index(
                fields=["tenant_id", "product", "is_active"],
                name="inventory_v_tenant__d8aa38_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "department", "code"),
                name="unique_tenant_cat_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "code"), name="unique_tenant_dept_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "slug"), name="unique_tenant_attribute_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "warehouse", "code"),
                name="unique_tenant_location_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "reservation_number"),
                name="unique_tenant_reservation_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "category", "code"),
                name="unique_tenant_subcat_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "abbreviation"), name="unique_tenant_uom_abbrev"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "name"), name="unique_tenant_uom_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendormanagedinventory",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "vmi_number"), name="unique_tenant_vmi_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="vmiproduct",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "vmi_agreement", "product"),
                name="unique_vmi_product",
            ),
        ),
    ]
